# -*- coding: utf-8 -*-
"""YOLO_SARD

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebook#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/krishnamnuwal/yolo-sard.ffa51021-7d04-4903-b7d9-83e7b3aa842f.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20260921/auto/storage/goog4_request%26X-Goog-Date%3D20260921T200057Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D8dda073bb995b797859dc3275ca598edf520182fb92b0427c9b7e2e1f3bb8bb5758c2278f23442b0e570d3f7acef1a81ad2a0d119137de05922c1c8f0365a7eb83ea72e784bce3656b9da0d0713beb88da47061d35d118972c56d2ed76f27b0d0b30936ebccd5b817c24b733ea3b30d95ae053344a781f060bac8d286bd87d0cdf690202c89217c309d9fc1a521df9164cf37f0a0d7b46a2853255c91d2a44854f8b91c02213e965280b2fbd7ee0c587d73c249fd80e44db6ded82d555717f6b5c702b9f1b0b0f85ad03bd65f9e245525e546893fc628f63b1d27d5a8074c37224d34071791a6f50c64c2290d1645087fb13023811b0a2504a394e17e2679ab0
"""

# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.
import kagglehub
sm1444_sard_yolo11_path = kagglehub.notebook_output_download('sm1444/sard-yolo11')

print('Data source import complete.')





import os
import shutil
from pathlib import Path

import cv2
import torch
from ultralytics import YOLO

BASE = Path("/kaggle/working")
DATA_ROOT = Path("/kaggle/input/search-and-rescue-image-dataset-sard")
RUN_DIR = BASE / "runs"
VIDEO_IN = Path("/kaggle/input/aerial-survivor-clip/drone_clip.mp4")
VIDEO_OUT = BASE / "survivors_detected.mp4"

RUN_DIR.mkdir(parents=True, exist_ok=True)



def build_yaml(dataset_root: Path, out_path: Path):
    images_train = dataset_root / "images" / "train"
    images_val = dataset_root / "images" / "val"
    yaml_text = (
        f"path: {dataset_root}\n"
        f"train: {images_train.relative_to(dataset_root)}\n"
        f"val: {images_val.relative_to(dataset_root)}\n"
        f"names:\n"
        f"  0: person\n"
    )
    out_path.write_text(yaml_text)
    return out_path

data_yaml = build_yaml(DATA_ROOT, BASE / "sard.yaml")
print(data_yaml.read_text())

device = 0 if torch.cuda.is_available() else "cpu"
print("device:", device)

model = YOLO("yolov8n.pt")

train_results = model.train(
    data=str(data_yaml),
    epochs=30,
    imgsz=640,
    batch=16,
    device=device,
    project=str(RUN_DIR),
    name="survivor_det",
    patience=8,
    optimizer="AdamW",
    lr0=0.002,
    cos_lr=True,
    mosaic=1.0,
    hsv_v=0.4,
    flipud=0.2,
    workers=2,
)

best_weights = Path(train_results.save_dir) / "weights" / "best.pt"
print("best weights:", best_weights)

metrics = YOLO(str(best_weights)).val(data=str(data_yaml), imgsz=640, device=device)
print("mAP50:", metrics.box.map50, "mAP50-95:", metrics.box.map)

def run_on_video(weights: Path, src: Path, dst: Path, conf=0.35, iou=0.5):
    detector = YOLO(str(weights))
    cap = cv2.VideoCapture(str(src))

    fps = cap.get(cv2.CAP_PROP_FPS) or 30
    w = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    h = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

    writer = cv2.VideoWriter(
        str(dst), cv2.VideoWriter_fourcc(*"mp4v"), fps, (w, h)
    )

    survivors_seen = 0
    frame_idx = 0
    while True:
        ok, frame = cap.read()
        if not ok:
            break

        result = detector.predict(
            frame, conf=conf, iou=iou, imgsz=640, device=device, verbose=False
        )[0]

        for box in result.boxes:
            x1, y1, x2, y2 = box.xyxy[0].int().tolist()
            score = float(box.conf[0])
            cv2.rectangle(frame, (x1, y1), (x2, y2), (0, 255, 0), 2)
            cv2.putText(
                frame,
                f"survivor {score:.2f}",
                (x1, max(0, y1 - 8)),
                cv2.FONT_HERSHEY_SIMPLEX,
                0.6,
                (0, 255, 0),
                2,
            )
            survivors_seen += 1

        cv2.putText(
            frame,
            f"frame {frame_idx}  detections so far: {survivors_seen}",
            (10, 30),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.7,
            (255, 255, 0),
            2,
        )
        writer.write(frame)
        frame_idx += 1

    cap.release()
    writer.release()
    return frame_idx, survivors_seen


frames, hits = run_on_video(best_weights, VIDEO_IN, VIDEO_OUT)
print(f"processed {frames} frames, total detections: {hits}")
print(f"output saved to: {VIDEO_OUT}")
