# -*- coding: utf-8 -*-
"""Untitled25.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yWOlVuehhwQU9R31orlEzWs0SEpZgDaB
"""

!pip install ultralytics
from ultralytics import YOLO

model = YOLO("/content/yolo26n.pt")

results = model.predict(
    source="/content/video1.mp4",
    save=True,
    project="/content/output",
    name="detect",
    exist_ok=True
)

import glob
import cv2

avi = glob.glob("/content/output/detect/*.avi")[0]
cap = cv2.VideoCapture(avi)

fps = cap.get(cv2.CAP_PROP_FPS)
w = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
h = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

out = cv2.VideoWriter(
    "/content/detected_video.mp4",
    cv2.VideoWriter_fourcc(*"mp4v"),
    fps, (w, h)
)

while True:
    ret, frame = cap.read()
    if not ret:
        break
    out.write(frame)

cap.release()
out.release()

print("Saved: /content/detected_video.mp4")

!ffmpeg -y -i /content/detected_video.mp4\
    -c:v libx264 -pix_fmt yuv420p -movflags +faststart \
    /content/detected_video2.mp4

from IPython.display import Video, display

display(Video("/content/detected_video2.mp4", embed=True))
