# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AD75uq57gI6thJnn8wZZP3UdxAuU17su
"""

import torch
import torch.nn as nn
import torchvision.transforms as transforms
import torchvision.transforms.v2.functional as F
import torchvision.datasets as datasets
import torch.utils.data.dataloader as Dataloader
import os
from PIL import Image
import matplotlib.pyplot as plt
import numpy as np
import glob
import cv2
from tqdm.auto import tqdm

import torch.utils.data as data

class Dataset(data.Dataset):
  def __init__(self, path, transform, id_):
    super().__init__()
    self.path = path
    self.transform = transform
    self.id_ = id_

  def __len__(self):
    return len(self.id_)

  def __getitem__(self, idx):
    img_folder = os.path.join(self.path, self.id_[idx], "images")
    img_files = glob.glob(os.path.join(img_folder, "*"))
    if not img_files:
        raise FileNotFoundError(f"No image found in {img_folder}")

    image = Image.open(img_files[0]).convert('RGB')
    image = self.transform(image)
    image = F.resize(image, (256, 256))

    path_mask = os.path.join(self.path, self.id_[idx], "masks")
    mask_files = glob.glob(os.path.join(path_mask, "*.png"))
    if not mask_files:
        raise FileNotFoundError(f"No masks found in {path_mask}")

    first_mask = cv2.imread(mask_files[0], cv2.IMREAD_GRAYSCALE)
    combined_mask = np.zeros_like(first_mask, dtype=np.uint8)

    for mask_file in mask_files:
      mask = cv2.imread(mask_file, cv2.IMREAD_GRAYSCALE)
      combined_mask = np.maximum(combined_mask, mask)

    combined_mask_tensor = torch.from_numpy(combined_mask).long()
    combined_mask_tensor[combined_mask_tensor == 255] = 1
    combined_mask_tensor = F.resize(combined_mask_tensor.unsqueeze(0), (256, 256)).squeeze(0)
    return image, combined_mask_tensor

path = "/content/drive/MyDrive/Datasets/stage1_train"
transform = transforms.ToTensor()
id_ = next(os.walk(path))[1]

full_data = Dataset(path, transform, id_)
generator = torch.Generator().manual_seed(42)
train_data, val_data = data.random_split(full_data, [0.8, 0.2], generator=generator)

train_loader = data.DataLoader(train_data, batch_size=8, shuffle=True, num_workers=2)
val_loader = data.DataLoader(val_data, batch_size=8, shuffle=False, num_workers=2)

image, mask = next(iter(train_loader))
print(image.shape)
print(mask.shape)


def compute_class_weights(dataset, num_classes=2):
    counts = torch.zeros(num_classes)
    for _, mask in dataset:
        for c in range(num_classes):
            counts[c] += (mask == c).sum()
    total = counts.sum()
    return total / (num_classes * counts)

class UNet(nn.Module):
  def __init__(self):
    super().__init__()
    self.conv1 = nn.Conv2d(3, 64, kernel_size = 3, stride = 1, padding=1)
    self.conv2 = nn.Conv2d(64, 64, kernel_size = 3, stride = 1, padding=1)
    self.maxpool1 = nn.MaxPool2d(2, 2)
    self.conv3 = nn.Conv2d(64, 128, kernel_size = 3, stride = 1, padding=1)
    self.conv4 = nn.Conv2d(128, 128, kernel_size = 3, stride = 1, padding=1)
    self.conv5 = nn.Conv2d(128, 256, kernel_size = 3, stride = 1, padding=1)
    self.conv6 = nn.Conv2d(256, 256, kernel_size = 3, stride = 1, padding=1)
    self.conv7 = nn.Conv2d(256, 512, kernel_size = 3, stride = 1, padding=1)
    self.conv8 = nn.Conv2d(512, 512, kernel_size = 3, stride = 1, padding=1)
    # self.conv9 = nn.Conv2d(512, 1024, kernel_size = 3, stride = 1, padding=1)
    # self.conv10 = nn.Conv2d(1024, 1024, kernel_size = 3, stride = 1, padding=1)
    # self.upconv1 = nn.ConvTranspose2d(1024, 512, kernel_size = 2, stride = 2)
    # self.conv11 = nn.Conv2d(1024, 512, kernel_size = 3, stride = 1, padding=1)
    # self.conv12 = nn.Conv2d(512, 512, kernel_size = 3, stride = 1, padding=1)
    self.upconv2 = nn.ConvTranspose2d(512, 256, kernel_size = 2, stride = 2)
    self.conv13 = nn.Conv2d(512, 256, kernel_size = 3, stride = 1, padding=1)
    self.conv14 = nn.Conv2d(256, 256, kernel_size = 3, stride = 1, padding=1)
    self.upconv3 = nn.ConvTranspose2d(256, 128, kernel_size = 2, stride = 2)
    self.conv15 = nn.Conv2d(256, 128, kernel_size = 3, stride = 1, padding=1)
    self.conv16 = nn.Conv2d(128, 128, kernel_size = 3, stride = 1, padding=1)
    self.upconv4 = nn.ConvTranspose2d(128, 64, kernel_size = 2, stride = 2)
    self.conv17 = nn.Conv2d(128, 64, kernel_size = 3, stride = 1, padding=1)
    self.conv18 = nn.Conv2d(64, 64, kernel_size = 3, stride = 1, padding=1)
    self.conv19 = nn.Conv2d(64, 2, kernel_size = 1, stride = 1)
    self.relu = nn.ReLU()

  def forward(self, x):
    x = self.relu(self.conv2(self.relu(self.conv1(x))))
    x1 = x
    x = self.relu(self.conv4(self.relu(self.conv3(self.maxpool1(x)))))
    x2 = x
    x = self.relu(self.conv6(self.relu(self.conv5(self.maxpool1(x)))))
    x3 = x
    x = self.relu(self.conv8(self.relu(self.conv7(self.maxpool1(x)))))
    # x4 = x
    # x = self.relu(self.conv10(self.relu(self.conv9(self.maxpool1(x)))))

    # x = torch.cat([self.upconv1(x), x4], dim=1)
    # x = self.relu(self.conv12(self.relu(self.conv11(x))))

    x = torch.cat([self.upconv2(x), x3], dim=1)
    x = self.relu(self.conv14(self.relu(self.conv13(x))))

    x = torch.cat([self.upconv3(x), x2], dim=1)
    x = self.relu(self.conv16(self.relu(self.conv15(x))))

    x = torch.cat([self.upconv4(x), x1], dim=1)
    x = self.relu(self.conv18(self.relu(self.conv17(x))))

    x = self.conv19(x)
    return x

def train(train_loader, val_loader, epochs, class_weights=None, lr=1e-3, device=None, resume = True,
          checkpoint_path='best_model.pth'):

    print(f'Using device: {device}')
    model = UNet().to(device)

    weight_tensor = class_weights.to(device) if class_weights is not None else None
    criterion = nn.CrossEntropyLoss(weight=weight_tensor)
    optimizer = torch.optim.Adam(model.parameters(), lr=lr)

    best_val_loss = float('inf')
    start_epoch = 1

    if resume and os.path.exists(checkpoint_path):
        checkpoint = torch.load(checkpoint_path, map_location=device)
        model.load_state_dict(checkpoint['model_state_dict'])
        optimizer.load_state_dict(checkpoint['optimizer_state_dict'])
        start_epoch = checkpoint['epoch']
        best_val_loss = checkpoint['val_loss']
        print(f'Resumed from checkpoint: epoch {start_epoch}, val loss {best_val_loss:.4f}')

    for epoch in range(start_epoch, epochs):
        model.train()
        running_train_loss = 0.0
        train_bar = tqdm(train_loader, desc=f'Epoch {epoch + 1}/{epochs} [train]', leave=False)
        for image, mask in train_bar:
            image, mask = image.to(device), mask.to(device)
            optimizer.zero_grad()
            out = model(image)
            loss = criterion(out, mask)
            loss.backward()
            optimizer.step()
            running_train_loss += loss.item() * image.size(0)
            train_bar.set_postfix(loss=loss.item())
        train_loss = running_train_loss / len(train_loader.dataset)

        model.eval()
        running_val_loss = 0.0
        val_bar = tqdm(val_loader, desc=f'Epoch {epoch + 1}/{epochs} [val]', leave=False)
        with torch.no_grad():
            for image, mask in val_bar:
                image, mask = image.to(device), mask.to(device)
                out = model(image)
                loss = criterion(out, mask)
                running_val_loss += loss.item() * image.size(0)
                val_bar.set_postfix(loss=loss.item())
        val_loss = running_val_loss / len(val_loader.dataset)

        print(f'Epoch {epoch + 1}/{epochs} | Train Loss: {train_loss:.4f} | Val Loss: {val_loss:.4f}')

        if val_loss < best_val_loss:
            best_val_loss = val_loss
            torch.save({
                'epoch': epoch + 1,
                'model_state_dict': model.state_dict(),
                'optimizer_state_dict': optimizer.state_dict(),
                'val_loss': val_loss,
            }, checkpoint_path)

    return model


device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

model = train(
    train_loader, val_loader, epochs=10, class_weights=None, device=device,
    checkpoint_path='/content/drive/MyDrive/Datasets/best_unet_model.pth',
)

image, mask = next(iter(val_loader))
image = F.resize(image, (256, 256))
image = image.to(device)
out = model(image)
plt.imshow(mask[0], cmap = 'gray')
plt.axis('off')
plt.show()
plt.imshow(out[0].argmax(dim=0).cpu(), cmap = 'gray')
plt.axis('off')
plt.show()